### ISSUE TITLE
README.md specific SDK native binary v6.53.1 version to download

### ISSUE THREAD

**Issue by noey-teerataninchat-tw** [pundixit/capacitor-pushiomanager#14]
Our team found that there was updated on README to download SDK native binary v6.53.1 (PR : https://github.com/pundixit/capacitor-pushiomanager/commit/21055967dd8722642d8fadc813eeb5920c92d073), which we notice that it is quite old version. May I ask the reasons on this. Will it be problems if we update the SDK version in the future.

<img width="956" alt="image" src="https://github.com/pundixit/capacitor-pushiomanager/assets/93980922/11a54a61-6040-4c97-bfd4-03e480c84765">

**Comment by neerhaj** [comment]
6.53.1 is the minimum required version.
 
If your app is using a newer version then you can continue to use that.
