### ISSUE TITLE
PushIOManager.declarePreference uses incorrect "value" parameter for iOS

### ISSUE THREAD

**Issue by ichaelpham** [pundixit/capacitor-pushiomanager#2]
Documentation suggests accepts PushIOManager.declarePreference(options: { key: string, label: string, type: string }) however on iOS this does not work.

Looks like the iOS version accepts "value" as a parameter not "key"
plugins/capacitor-pushiomanager/ios/Plugin/PushIOHandler.swift

```
@objc public func declarePreference(key:String, value:String, type:PIOPreferenceType, error:NSErrorPointer) -> Void  {
        
        PushIOManager.sharedInstance().declarePreference(key, label: value, type: type, error: error)

}
```

**Comment by neerhaj** [comment]
This looks similar to #1 .

**Comment by neerhaj** [comment]
`PushIOManager.declarePreference({ key: "sampleKey", label: "sampleLabel", type: "STRING" })` now works on iOS as well.
