### ISSUE TITLE
Intergrating SDK launches requests Android runtime permissions automatically on app launch

### ISSUE THREAD

**Issue by ichaelpham** [pundixit/capacitor-pushiomanager#3]
Our app was designed to contextually request permissions from users after displaying onboarding information. Integrating the Android SDK seems to automatically requestPermissions() from device on app launch without it being prompted by the user

**Comment by ichaelpham** [comment]
`<activity
            android:name="com.pushio.manager.PIOPermissionsActivity"
            android:launchMode="singleTask"
            android:theme="@android:style/Theme.Translucent.NoTitleBar" />`

Within the plugins android manifest appears to be launching the permissions prompt. Is this needed?

**Comment by neerhaj** [comment]
The registerApp API has been updated to,

`PushIOManager.registerApp({ pushNotificationsEnabled: false, useLocation: true })`

Passing `false` for `pushNotificationsEnabled` will not bring up the push-notification runtime permission dialog.

When your app needs to request for push-notification permission, call this API again. Same goes for location permission.

Few things to note,

- This requires Responsys Android SDK v6.53.1, you can get it from [here](https://www.oracle.com/downloads/applications/cx/responsys-mobile-sdk.html).

- Your app must target API 33 or above to control when to show the push-notification permission dialog. The location permission dialog works for lower API levels as well.

- iOS behaviour remains the same as before and ignores both the parameters.
