### ISSUE TITLE
PushIOManager.getRegisteredUserId() returns data in correct format

### ISSUE THREAD

**Issue by ichaelpham** [pundixit/capacitor-pushiomanager#5]
The type definitions define this method to return success / failure callback.

On Android this is returns
`{ value: userId }`

On iOS this is returns
`{ success: userId }`

Both platforms should return consistent data format

**Comment by neerhaj** [comment]
Both platforms now return `{ userId:  sampleuser@example.com }`

Note the change in response object from `value`/`success` to `userId`.
